/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Parameter.h"
#include "CMD.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0    (GUI_ID_USER + 0x00)
#define ID_LISTVIEW_0    (GUI_ID_USER + 0x01)
#define ID_EDIT_0    (GUI_ID_USER + 0x02)
#define ID_BUTTON_0    (GUI_ID_USER + 0x03)
#define ID_BUTTON_1    (GUI_ID_USER + 0x04)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/

//WM_HWIN _hWin;



static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "MotorPara", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 2, 2, 786, 359, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 28, 373, 141, 33, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 495, 398, 118, 46, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 636, 398, 118, 46, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};
 
void LoadData_mp(WM_HWIN hItem)
{
//    //LISTVIEW_AddRow(hItem, NULL);			
//    LISTVIEW_SetItemText(hItem, 0, 0, "1");
//    LISTVIEW_SetItemText(hItem, 1, 0, "0.00397");
//    LISTVIEW_SetItemText(hItem, 2, 0, "100");
//    LISTVIEW_SetItemText(hItem, 3, 0, "500");
//    LISTVIEW_SetItemText(hItem, 4, 0, "5000");
//    LISTVIEW_SetItemText(hItem, 5, 0, "Left");
	
    GetParameter();
  	for(u8 i=0;i<MotorPortNum;i++)
    {
      LISTVIEW_AddRow(hItem, NULL);	
      LISTVIEW_SetItemText(hItem, 0, i, ConvertU32ToAscii(i+1));
      LISTVIEW_SetItemText(hItem, 1, i, ConvertFloatToAscii(Parameter.PulseK[i]));
      LISTVIEW_SetItemText(hItem, 2, i, ConvertFloatToAscii(Parameter.AxisLength[i]));
      LISTVIEW_SetItemText(hItem, 3, i, ConvertFloatToAscii(Parameter.RunSpeed[i]));
      LISTVIEW_SetItemText(hItem, 4, i, ConvertFloatToAscii(Parameter.AccSpeed[i]));
      if(Parameter.LimitMode[i]==0)
        LISTVIEW_SetItemText(hItem, 5, i, "Left");
      else if(Parameter.LimitMode[i]==1)
        LISTVIEW_SetItemText(hItem, 5, i, "Right");
    }

//  	for(u8 i=0;i<MotorPortNum;i++)
//    {
//      LISTVIEW_AddRow(hItem, NULL);	
//      LISTVIEW_SetItemText(hItem, 0, i, "1");
//      LISTVIEW_SetItemText(hItem, 1, i, "0.00937");
//      LISTVIEW_SetItemText(hItem, 2, i, "100");
//      LISTVIEW_SetItemText(hItem, 3, i, "1000");
//      LISTVIEW_SetItemText(hItem, 4, i, "20000");
//      if(Parameter.LimitMode[i]==0)
//        LISTVIEW_SetItemText(hItem, 5, i, "Left");
//      else if(Parameter.LimitMode[i]==1)
//        LISTVIEW_SetItemText(hItem, 5, i, "Right");
//    }
}

static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'MotorPara'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Listview'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
    LISTVIEW_AddColumn(hItem, 100, "AxisID", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 137, "PulseK", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 137, "Length[mm]", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 137, "Speed", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 137, "ACC", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 137, "XW", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetFont(hItem, GUI_FONT_24_ASCII);
    LISTVIEW_SetRowHeight(hItem, 54);
    LISTVIEW_SetHeaderHeight(hItem, 32);
    LISTVIEW_SetGridVis(hItem, 1);
	LISTVIEW_EnableCellSelect(hItem,1);
    LoadData_mp(hItem);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "123");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_32_ASCII);
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_32_ASCII);
    BUTTON_SetText(hItem, "Save");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_32_ASCII);
    BUTTON_SetText(hItem, "Back");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_LISTVIEW_0: // Notifications sent by 'Listview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
        int rowIndex=LISTVIEW_GetSel(hItem);
        int colIndex=LISTVIEW_GetSelCol(hItem);
        ShowNumKeyboard2(pMsg->hWin,LISTVIEW_SetItemText,ID_LISTVIEW_0,colIndex,rowIndex);
//		char readBuff[20]={0};
//		LISTVIEW_GetItemText(hItem,colIndex,rowIndex,readBuff,20);
//		int oldValue=ConvertAsciiTou32(readBuff);
//		char* newValue = ConvertU32ToAscii(oldValue+100);
//		LISTVIEW_SetItemText(hItem, colIndex, rowIndex, newValue);
		  
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        //WM_HideWindow(_hWin);
        GUI_EndDialog(pMsg->hWin, 0);
        CreateWorkForm();
        break;
      case WM_NOTIFICATION_RELEASED:
        
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}


WM_HWIN CreateMotorPara(void) 
{ 
//  if(_hWin==NULL)
//  {
//    _hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
//  }
//  else
//  {
//    WM_ShowWindow(_hWin); //无法显示，这种方式可能要在程序创建之初就要把所有窗体全部实例化，占用内存太多
//  }
//  return _hWin;
  WM_HWIN _hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return _hWin;
}
