/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FontXYQ_YH_20_20.c                                    *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      20                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  20                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: K:\GUI\FontXYQ.txt                              *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFontXYQ_YH_20_20;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_4E0A[ 40] = { /* code 4E0A */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______XX,XXXXX___,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_4E0B[ 40] = { /* code 4E0B */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XXXXXX__,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______XX,X_______,
  ______X_,XX______,
  ______X_,__XX____,
  ______X_,___XX___,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_4E1D[ 40] = { /* code 4E1D */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____X___,__X_____,
  ___X____,_X______,
  ___X____,_X______,
  __X___X_,X___X___,
  _X___X__,X__X____,
  XXXXX__X,XXXX____,
  ____X___,__X_____,
  ___X____,_X______,
  __X__X__,X__XX___,
  _XXXX__X,XXX_____,
  ________,________,
  XXXXXXXX,XXXXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_4EF6[ 40] = { /* code 4EF6 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___X____,_X______,
  __XX__X_,_X______,
  __X___X_,_X______,
  __X__XXX,XXXXXX__,
  _XX__X__,_X______,
  XXX_X___,_X______,
  X_X_____,_X______,
  __X_XXXX,XXXXXX__,
  __X_____,_X______,
  __X_____,_X______,
  __X_____,_X______,
  __X_____,_X______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_4F7F[ 40] = { /* code 4F7F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___X____,X_______,
  __XX____,X_______,
  __X_XXXX,XXXXXX__,
  __X_____,X_______,
  _XX__XXX,XXXXX___,
  XXX__X__,X___X___,
  X_X__XXX,XXXXX___,
  __X__X__,X___X___,
  __X__XX_,X_______,
  __X___XX,X_______,
  __X___XX,XXX_____,
  __X_XX__,__XXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_505C[ 40] = { /* code 505C */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___X____,XX______,
  ___XXXXX,XXXXXX__,
  __X_____,________,
  __X__XXX,XXXX____,
  _XX__X__,___X____,
  XXX__XXX,XXXX____,
  X_X_____,________,
  __X_XXXX,XXXXXX__,
  __X_X___,_____X__,
  __X__XXX,XXXXX___,
  __X_____,_X______,
  __X___XX,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_516C[ 40] = { /* code 516C */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____X__,X_______,
  ____X___,XX______,
  ___XX___,_X______,
  __XX____,__X_____,
  _XX_____,__XX____,
  XX____X_,____X___,
  _____X__,________,
  _____X__,X_______,
  ____X___,_X______,
  ___X____,__X_____,
  __X___XX,XXX_____,
  _XXXXX__,___X____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_51FA[ 40] = { /* code 51FA */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______X_,________,
  _X____X_,____X___,
  _X____X_,____X___,
  _X____X_,____X___,
  _XXXXXXX,XXXXX___,
  ______X_,____X___,
  _X____X_,____X___,
  _X____X_,____X___,
  _X____X_,____X___,
  _X____X_,____X___,
  _XXXXXXX,XXXXX___,
  ________,____X___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_524D[ 40] = { /* code 524D */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____X___,__X_____,
  _____X__,XX______,
  XXXXXXXX,XXXXXX__,
  ________,________,
  _XXXXXX_,_X__X___,
  _X____X_,_X__X___,
  _XXXXXX_,_X__X___,
  _X____X_,_X__X___,
  _XXXXXX_,_X__X___,
  _X____X_,_X__X___,
  _X____X_,____X___,
  _X__XXX_,_XXXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_52A8[ 40] = { /* code 52A8 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,_X______,
  __XXXXX_,_X______,
  ________,_X______,
  _______X,XXXXX___,
  ________,_X__X___,
  _XXXXXXX,_X__X___,
  ___X____,_X__X___,
  ___X____,_X__X___,
  __X__X__,X___X___,
  __X_XXX_,X___X___,
  _XXX__XX,____X___,
  ______X_,__XXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_53D6[ 40] = { /* code 53D6 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXX_,________,
  _X___X_X,XXXXX___,
  _X___X_X,____X___,
  _XXXXX_X,____X___,
  _X___X_X,___X____,
  _XXXXX__,X__X____,
  _X___X__,X__X____,
  _X___X__,_XX_____,
  _X_XXXXX,_XX_____,
  XXX__X__,XXX_____,
  _____X_X,X__XX___,
  _____XXX,____XX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_53F3[ 40] = { /* code 53F3 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXX___,
  _____X__,________,
  ____X___,________,
  ___XXXXX,XXXX____,
  __XX____,___X____,
  _X_X____,___X____,
  X__X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_53F8[ 40] = { /* code 53F8 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,XXXXX___,
  ________,____X___,
  ________,____X___,
  _XXXXXXX,XXX_X___,
  ________,____X___,
  ________,____X___,
  __XXXXXX,X___X___,
  __X_____,X___X___,
  __X_____,X___X___,
  __XXXXXX,X___X___,
  __X_____,____X___,
  ________,XXXXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_540E[ 40] = { /* code 540E */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,_XXXX___,
  __XXXXXX,X_______,
  __X_____,________,
  __X_____,________,
  __XXXXXX,XXXXXX__,
  __X_____,________,
  __X_____,________,
  __X_XXXX,XXXX____,
  __X_X___,___X____,
  _X__X___,___X____,
  _X__XXXX,XXXX____,
  X___X___,___X____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_5411[ 40] = { /* code 5411 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  _____X__,________,
  _XXXXXXX,XXXXX___,
  _X______,____X___,
  _X______,____X___,
  _X__XXXX,XX__X___,
  _X__X___,_X__X___,
  _X__X___,_X__X___,
  _X__XXXX,XX__X___,
  _X__X___,____X___,
  _X______,____X___,
  _X______,_XXXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_542F[ 40] = { /* code 542F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,________,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,________,
  __X_____,________,
  __X_XXXX,XXXXX___,
  __X_X___,____X___,
  _X__X___,____X___,
  _X__XXXX,XXXXX___,
  X___X___,____X___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_59CB[ 40] = { /* code 59CB */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X_____,_X______,
  __X_____,X_______,
  __X____X,___X____,
  XXXXX_X_,____X___,
  _X__X_XX,XXXXX___,
  _X__XXXX,_____X__,
  _X__X___,________,
  _X_X__XX,XXXXX___,
  __XX__X_,____X___,
  __XXX_X_,____X___,
  _X__XXXX,XXXXX___,
  X_____X_,____X___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_5B9A[ 40] = { /* code 5B9A */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______X_,________,
  ______XX,________,
  _XXXXXXX,XXXXX___,
  _X______,____X___,
  ________,________,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  ___X___X,________,
  ___X___X,XXXXX___,
  __XX___X,________,
  _XXXX__X,________,
  XX___XXX,XXXXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_5DE6[ 40] = { /* code 5DE6 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______X_,________,
  _____X__,________,
  __XXXXXX,XXXXXX__,
  _____X__,________,
  _____X__,________,
  ____X___,________,
  ____XXXX,XXXXX___,
  ___X____,X_______,
  ___X____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  _X_XXXXX,XXXXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_5F00[ 40] = { /* code 5F00 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXXXX___,
  ____X___,_X______,
  ____X___,_X______,
  ____X___,_X______,
  ____X___,_X______,
  XXXXXXXX,XXXXXX__,
  ____X___,_X______,
  ____X___,_X______,
  ____X___,_X______,
  ___X____,_X______,
  __XX____,_X______,
  _XX_____,_X______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_6253[ 40] = { /* code 6253 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___X____,________,
  ___X__XX,XXXXX___,
  _XXXXX__,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X_X__,__X_____,
  __XXX___,__X_____,
  _X_X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  _XXX___X,XXX_____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_6280[ 40] = { /* code 6280 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X_____,_X______,
  __X_____,_X______,
  XXXXXXXX,XXXXXX__,
  __X_____,_X______,
  __X_____,_X______,
  __XX_XXX,XXXXX___,
  _XX___X_,____X___,
  X_X___XX,___X____,
  __X____X,X_X_____,
  __X_____,XX______,
  __X___XX,XXXX____,
  XXX_XX__,____XX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_62D3[ 40] = { /* code 62D3 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X__XXX,XXXXX___,
  __X_____,X_______,
  XXXXX___,X_______,
  __X____X,________,
  __X___X_,________,
  __XXX_XX,XXXXX___,
  XXX__XX_,____X___,
  __X_X_X_,____X___,
  __XX__X_,____X___,
  __X___X_,____X___,
  __X___XX,XXXXX___,
  XXX___X_,____X___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_62E9[ 40] = { /* code 62E9 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X__XXX,XXXXX___,
  __X___X_,___XX___,
  XXXXX__X,___X____,
  __X_____,XXX_____,
  __X____X,X_XX____,
  __XXXXX_,____XX__,
  XXX_____,_X______,
  __X___XX,XXXXX___,
  __X_____,_X______,
  __X_XXXX,XXXXXX__,
  __X_____,_X______,
  XXX_____,_X______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_63A7[ 40] = { /* code 63A7 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X_____,X_______,
  __X_____,_X______,
  __X__XXX,XXXXX___,
  XXXX_X__,____X___,
  __X____X,__XX____,
  __X__XX_,___XX___,
  __XXXX__,_____X__,
  XXX__XXX,XXXXX___,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  XXX_XXXX,XXXXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_6587[ 40] = { /* code 6587 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______X_,________,
  _______X,________,
  XXXXXXXX,XXXXXX__,
  ___X____,__X_____,
  ___X____,__X_____,
  ____X___,_X______,
  ____X___,_X______,
  _____X__,X_______,
  ______XX,________,
  _____XXX,X_______,
  __XXX___,_XXX____,
  XX______,___XXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_667A[ 40] = { /* code 667A */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX_____,XXXXX___,
  XXXXXXX_,X___X___,
  ___X____,X___X___,
  XXXXXXX_,XXXXX___,
  ___XX___,X___X___,
  __X__XX_,________,
  XXXXXXXX,XXXX____,
  __X_____,___X____,
  __XXXXXX,XXXX____,
  __X_____,___X____,
  __XXXXXX,XXXX____,
  __X_____,___X____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_6709[ 40] = { /* code 6709 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXXXXX__,
  ____X___,________,
  ___XXXXX,XXXX____,
  __XX____,___X____,
  _X_XXXXX,XXXX____,
  X__X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___X____,XXXX____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_673A[ 40] = { /* code 673A */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X___XX,XXX_____,
  __X___X_,__X_____,
  XXXXX_X_,__X_____,
  __X___X_,__X_____,
  __X___X_,__X_____,
  _XXX__X_,__X_____,
  _XX_X_X_,__X_____,
  X_X___X_,__X_____,
  X_X___X_,__X__X__,
  __X__X__,__X__X__,
  __X__X__,__X__X__,
  __X_X___,__XXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_6B22[ 40] = { /* code 6B22 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,X_______,
  _XXXXX__,X_______,
  _____X_X,XXXXXX__,
  _X___X_X,_____X__,
  __X__XX_,_X__X___,
  ___XX___,_X______,
  ___XX___,_X______,
  ____XX__,_X______,
  ___X_X__,X_X_____,
  __XX__XX,X__X____,
  __X___XX,___XX___,
  _X___X__,____XX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_6B62[ 40] = { /* code 6B62 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _______X,________,
  _______X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,XXXX____,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  _XXXXXXX,XXXXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_6D88[ 40] = { /* code 6D88 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X___X__,X___X___,
  __X__XX_,X__X____,
  ___X__X_,X_X_____,
  _X___XXX,XXXXX___,
  _XX__X__,____X___,
  __X__X__,____X___,
  _____XXX,XXXXX___,
  __X__X__,____X___,
  __X__XXX,XXXXX___,
  __X__X__,____X___,
  _X___X__,____X___,
  _X___X__,_XXXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_70B9[ 40] = { /* code 70B9 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______X_,________,
  ______XX,XXXXXX__,
  ______X_,________,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  ________,________,
  __X_X___,X__X____,
  _X__X___,X___X___,
  _X___X__,_X__X___,
  X____X__,_X___X__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_7528[ 40] = { /* code 7528 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  _X_____X,____X___,
  _X_____X,_XXXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_786E[ 40] = { /* code 786E */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,X_______,
  _XXXXX_X,XXXX____,
  ___X__X_,__X_____,
  __X__XXX,XXXXX___,
  __XXX_X_,_X__X___,
  _XX_X_XX,XXXXX___,
  _XX_X_X_,_X__X___,
  X_X_X_X_,_X__X___,
  __X_X_XX,XXXXX___,
  __XXX_X_,_X__X___,
  __X__XX_,_X__X___,
  _____X__,_XXXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_79D1[ 40] = { /* code 79D1 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XX__,___X____,
  _XXX___X,___X____,
  ___X____,X__X____,
  ___X____,_X_X____,
  _XXXXXX_,___X____,
  ___X___X,___X____,
  __XXX___,X__X____,
  __XX_X__,___X____,
  _X_X____,_XXXXX__,
  _X_X_XXX,X__X____,
  ___X____,___X____,
  ___X____,___X____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_80F6[ 40] = { /* code 80F6 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXX___,X_______,
  _X__X___,_X______,
  _X__X_XX,XXXXXX__,
  _XXXX___,________,
  _X__X___,X_XX____,
  _X__X_XX,___XX___,
  _X__XX_X,___X_X__,
  _XXXX___,X_XX____,
  _X__X___,X_X_____,
  _X__X___,_X______,
  XX__X__X,X_XX____,
  X_XXXXX_,____XX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_80FD[ 40] = { /* code 80FD */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XX____,X____X__,
  _X___X__,X__XX___,
  XXXXXXX_,XXX__X__,
  _______X,X____X__,
  _XXXXXX_,XXXXX___,
  _X____X_,________,
  _XXXXXX_,X____X__,
  _X____X_,X__XX___,
  _XXXXXX_,XXX_____,
  _X____X_,X____X__,
  _X____X_,X____X__,
  _X__XXX_,XXXXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_87BA[ 40] = { /* code 87BA */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___X__XX,XXXXX___,
  ___X__X_,_X__X___,
  _XXXX_XX,XXXXX___,
  _X_XX_X_,_X__X___,
  _X_XX_XX,XXXXX___,
  _X_XX___,X_XX____,
  _XXXX_XX,XXX_____,
  _X_X____,X__XX___,
  ___XX_XX,XXXXXX__,
  ___X_X__,XX_X____,
  XXXXXXXX,_X__X___,
  _____XX_,XX___X__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_8FCE[ 40] = { /* code 8FCE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X_____X,X_______,
  __X__XXX,_XXXX___,
  ___X_X__,_X__X___,
  _____X__,_X__X___,
  _XX__X__,_X__X___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  __X__X__,XXXXX___,
  __X__XXX,_X______,
  __X__X__,_X______,
  XX_X____,________,
  X___XXXX,XXXXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_9009[ 40] = { /* code 9009 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X____X_,_X______,
  __X__XX_,_X______,
  ___X_XXX,XXXXX___,
  ____X___,_X______,
  XXX_____,_X______,
  __X_XXXX,XXXXXX__,
  __X____X,__X_____,
  __X____X,__X__X__,
  __X___XX,__X__X__,
  __X__XX_,__XXXX__,
  XX_X____,________,
  X___XXXX,XXXXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_91CD[ 40] = { /* code 91CD */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXXXX___,
  ______X_,________,
  XXXXXXXX,XXXXXX__,
  ______X_,________,
  __XXXXXX,XXXX____,
  __X___X_,___X____,
  __XXXXXX,XXXX____,
  __X___X_,___X____,
  __XXXXXX,XXXX____,
  ______X_,________,
  _XXXXXXX,XXXXX___,
  ______X_,________,
  XXXXXXXX,XXXXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontXYQ_YH_20_20_9650[ 40] = { /* code 9650 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXX_XX,XXXX____,
  _X__X_X_,___X____,
  _X_X__XX,XXXX____,
  _X_X__X_,___X____,
  _X_X__X_,___X____,
  _X__X_XX,XXXX____,
  _X__X_X_,X___X___,
  _X__X_X_,X__X____,
  _XXXX_X_,_XX_____,
  _X____X_,XXX_____,
  _X____XX,__XX____,
  _X____X_,___XX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontFontXYQ_YH_20_20_CharInfo[43] = {
   {  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_4E0A } /* code 4E0A */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_4E0B } /* code 4E0B */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_4E1D } /* code 4E1D */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_4EF6 } /* code 4EF6 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_4F7F } /* code 4F7F */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_505C } /* code 505C */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_516C } /* code 516C */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_51FA } /* code 51FA */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_524D } /* code 524D */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_52A8 } /* code 52A8 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_53D6 } /* code 53D6 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_53F3 } /* code 53F3 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_53F8 } /* code 53F8 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_540E } /* code 540E */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_5411 } /* code 5411 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_542F } /* code 542F */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_59CB } /* code 59CB */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_5B9A } /* code 5B9A */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_5DE6 } /* code 5DE6 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_5F00 } /* code 5F00 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_6253 } /* code 6253 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_6280 } /* code 6280 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_62D3 } /* code 62D3 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_62E9 } /* code 62E9 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_63A7 } /* code 63A7 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_6587 } /* code 6587 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_667A } /* code 667A */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_6709 } /* code 6709 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_673A } /* code 673A */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_6B22 } /* code 6B22 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_6B62 } /* code 6B62 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_6D88 } /* code 6D88 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_70B9 } /* code 70B9 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_7528 } /* code 7528 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_786E } /* code 786E */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_79D1 } /* code 79D1 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_80F6 } /* code 80F6 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_80FD } /* code 80FD */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_87BA } /* code 87BA */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_8FCE } /* code 8FCE */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_9009 } /* code 9009 */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_91CD } /* code 91CD */
  ,{  14,  14,  2, acGUI_FontFontXYQ_YH_20_20_9650 } /* code 9650 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop42 = {
   0x9650 /* first character */
  ,0x9650 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 42] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop41 = {
   0x91CD /* first character */
  ,0x91CD /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 41] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop42 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop40 = {
   0x9009 /* first character */
  ,0x9009 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 40] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop41 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop39 = {
   0x8FCE /* first character */
  ,0x8FCE /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 39] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop40 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop38 = {
   0x87BA /* first character */
  ,0x87BA /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 38] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop39 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop37 = {
   0x80FD /* first character */
  ,0x80FD /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 37] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop38 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop36 = {
   0x80F6 /* first character */
  ,0x80F6 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 36] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop37 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop35 = {
   0x79D1 /* first character */
  ,0x79D1 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 35] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop36 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop34 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 34] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop33 = {
   0x7528 /* first character */
  ,0x7528 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 33] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop32 = {
   0x70B9 /* first character */
  ,0x70B9 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 32] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop31 = {
   0x6D88 /* first character */
  ,0x6D88 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 31] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop30 = {
   0x6B62 /* first character */
  ,0x6B62 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 30] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop29 = {
   0x6B22 /* first character */
  ,0x6B22 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 29] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop28 = {
   0x673A /* first character */
  ,0x673A /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 28] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop27 = {
   0x6709 /* first character */
  ,0x6709 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 27] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop26 = {
   0x667A /* first character */
  ,0x667A /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 26] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop25 = {
   0x6587 /* first character */
  ,0x6587 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 25] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop24 = {
   0x63A7 /* first character */
  ,0x63A7 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 24] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop23 = {
   0x62E9 /* first character */
  ,0x62E9 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 23] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop22 = {
   0x62D3 /* first character */
  ,0x62D3 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 22] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop21 = {
   0x6280 /* first character */
  ,0x6280 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 21] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop20 = {
   0x6253 /* first character */
  ,0x6253 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 20] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop19 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 19] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop18 = {
   0x5DE6 /* first character */
  ,0x5DE6 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 18] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop17 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 17] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop16 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 16] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop15 = {
   0x542F /* first character */
  ,0x542F /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 15] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop14 = {
   0x5411 /* first character */
  ,0x5411 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 14] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop13 = {
   0x540E /* first character */
  ,0x540E /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 13] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop12 = {
   0x53F8 /* first character */
  ,0x53F8 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 12] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop11 = {
   0x53F3 /* first character */
  ,0x53F3 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 11] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop10 = {
   0x53D6 /* first character */
  ,0x53D6 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[ 10] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop9 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[  9] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop8 = {
   0x524D /* first character */
  ,0x524D /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[  8] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop7 = {
   0x51FA /* first character */
  ,0x51FA /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[  7] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop6 = {
   0x516C /* first character */
  ,0x516C /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[  6] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop5 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[  5] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop4 = {
   0x4F7F /* first character */
  ,0x4F7F /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[  4] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop3 = {
   0x4EF6 /* first character */
  ,0x4EF6 /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[  3] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop2 = {
   0x4E1D /* first character */
  ,0x4E1D /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[  2] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontXYQ_YH_20_20_Prop1 = {
   0x4E0A /* first character */
  ,0x4E0B /* last character  */
  ,&GUI_FontFontXYQ_YH_20_20_CharInfo[  0] /* address of first character */
  ,&GUI_FontFontXYQ_YH_20_20_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFontXYQ_YH_20_20 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,20 /* height of font  */
  ,20 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFontXYQ_YH_20_20_Prop1}
  ,16 /* Baseline */
  ,8 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

